### ISSUE TITLE
Possible merge with PlayerRatings package? 

### ISSUE THREAD

**Issue by rdatasculptor** [Schw4rz/csgo_glicko2#2]
I tried your code and it worked well for me. Thank you for sharing!
There is one thing I rather miss and that is a ratings update of all opponents in one go, giving a data frame wit a match history. A bit like the way the PlayerRatings package deals with it. 

In fact, as you almost certain know, that paclage has a function for the Glicko algorithm, but it lacks a Glicko-2's. Just a thought, but could there be a possibility of addingyour code to that package? 

Best rehards

**Comment by Schw4rz** [comment]
Glad that you like my code and thanks for your suggestion. I would love to see an implementation of the Glicko-2 algorithm in the PlayerRatings package, but not with this code.

Explanation: My code was written in "one go" and for a single purpose. It is a direct implementation of Glickman's example (see [here](http://www.glicko.net/glicko/glicko2.pdf)) and lacks testing, generality (at least partly, e.g. the mentioned data frame with history) and also performance (all rating systems in the PlayerRatings package are implemented in C for instance). 

Of course anyone can feel free to use (parts of) my code and start working on an implementation for the Player Ratings package. I feel i am too busy at the moment to consider doing that.

KR

Sebastian

**Comment by rdatasculptor** [comment]
Dear Sebastian,

Thank you very much for your response.  Ofcourse I completely understand your explanation. I think my main concern is the possibility to update the players rating and the ratings of the opponents in one go. Maybe I'll give it a try myself using your code as a start. Thanks again for sharing.

Kind regards,
Jelle

**Comment by znmeb** [comment]
@Schw4rz Is the PlayerRatings source online somewhere? I couldn't find a repository link in its DESCRIPTION file.

**Comment by rdatasculptor** [comment]
Do you mean this? https://github.com/cran/PlayerRatings/tree/master/R

Kind regards,
Jelle

**Comment by Schw4rz** [comment]
As @rdatasculptor pointed out there is a copy of the source files on [GitHub](https://github.com/cran/PlayerRatings). Also you can always download the Package Source directly from [CRAN](https://cran.r-project.org/web/packages/PlayerRatings/index.html) (which should be the same in this case). You can also find the contact addresses for the authors and maintainers in the DESCRIPTION file. 

But it seems like there is no other repository online where you could directly propose changes or make commits. So i guess you would have to contact them directly.

KR

Sebastian
